name: Deploy Docusaurus to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: write   # allow pushing commits
  pages: write      # allow requesting Pages builds
  id-token: write   # needed by some page deployments

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
